### ISSUE TITLE
How to run test file

### ISSUE THREAD

**Issue by amiiy** [I1820/mongo#1]
Thank you for your great solution.
assume `go` installed in my machine, how can I run the test file?
if `go` is not installed, is there any way to change this test file to executable file?

**Comment by 1995parham** [comment]
Thank you for using it.
Test code was written by Golang, for running it you must build it:
```
$ go build ./...
```
After the build, you have its executable in your operating system.
you can cross-compile it if you want.

**Comment by amiiy** [comment]
Cool!
